set APP_NAME=%1
set VERSION=%2
set BASE_PATH=%3
set REPO_REGISTRY=%4
set REPO_REGISTRY_NAMESPACE=%5
docker build -t %REPO_REGISTRY%/%REPO_REGISTRY_NAMESPACE%/%APP_NAME%:%VERSION% -f %BASE_PATH%\deploy\docker\DockerFile %BASE_PATH%