server:
  port: 9001
  tomcat:
    accesslog:
      enabled: true
      pattern: '%t %h %a -> %A %S %H "%r" len: %b resp: %s cost: %D thread: %I'
    basedir: ./
  servlet:
    context-path: /oauth2-thirdpart

spring:
  application:
    name: goauth2-thirdpart
  profiles:
    active: dev #默认为开发环境