#!/bin/bash

USERNAME=ryougishikiiiii
REGISTRY=$REPO_REGISTRY
NAMESPACE=$REPO_REGISTRY_NAMESPACE
PROJECT=$1
VERSION=$2

docker login -u $USERNAME $REGISTRY

docker pull $REGISTRY/$NAMESPACE/$PROJECT:$VERSION
docker tag $REGISTRY/$NAMESPACE/$PROJECT:$VERSION $PROJECT:$VERSION
