#!/bin/bash

REGISTRY=$REPO_REGISTRY
NAMESPACE=$REPO_REGISTRY_NAMESPACE
PROJECT=$1
VERSION=$2

docker stop $PROJECT
docker rm $PROJECT 

docker rmi $PROJECT:$VERSION
docker rmi $REGISTRY/$NAMESPACE/$PROJECT:$VERSION
