server:
  port: 9001
  tomcat:
    accesslog:
      enabled: true
      pattern: '%t %h %a -> %A %S %H "%r" len: %b resp: %s cost: %D thread: %I'
    basedir: ./
  servlet:
    context-path: /cloud

service:
  port: 19001

spring:
  application:
    name: gcloud

logging:
  level:
    com.gill.user: debug

oss:
  bucket: ${OSS_BUCKET}
  public-resource-path: ${OSS_PUBLIC_PATH}

dubbo:
  protocol:
    port: ${service.port}
  registry:
    address: zookeeper://${ZOOKEEPER_HOST}:${ZOOKEEPER_PORT}