server:
  port: 9001
  tomcat:
    accesslog:
      enabled: true
      pattern: '%t %h %a -> %A %S %H "%r" len: %b resp: %s cost: %D thread: %I'
    basedir: ./
  servlet:
    context-path: /cloud

service:
  port: 19001

spring:
  application:
    name: gcloud
  profiles:
    active: self

logging:
  level:
    com.gill.user: debug